# TCL File Generated by Component Editor 11.1sp2
# Sat Oct 20 19:44:30 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | AM2301 "AM2301" v1.0
# | Zhizhou Li 2012.10.20.19:44:30
# | Thermel and mosture sensor
# | 
# | H:/My Documents/GitHub/grid/qsys_root/AM2301.v
# | 
# |    ./AM2301.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module AM2301
# | 
set_module_property DESCRIPTION "Thermel and mosture sensor"
set_module_property NAME AM2301
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo
set_module_property AUTHOR "Zhizhou Li"
set_module_property DISPLAY_NAME AM2301
set_module_property TOP_LEVEL_HDL_FILE AM2301.v
set_module_property TOP_LEVEL_HDL_MODULE AM2301
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME AM2301
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file AM2301.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter high_width INTEGER 20
set_parameter_property high_width DEFAULT_VALUE 20
set_parameter_property high_width DISPLAY_NAME high_width
set_parameter_property high_width TYPE INTEGER
set_parameter_property high_width UNITS None
set_parameter_property high_width AFFECTS_GENERATION false
set_parameter_property high_width HDL_PARAMETER true
add_parameter start_width INTEGER 1000
set_parameter_property start_width DEFAULT_VALUE 1000
set_parameter_property start_width DISPLAY_NAME start_width
set_parameter_property start_width TYPE INTEGER
set_parameter_property start_width UNITS None
set_parameter_property start_width AFFECTS_GENERATION false
set_parameter_property start_width HDL_PARAMETER true
add_parameter start INTEGER 0
set_parameter_property start DEFAULT_VALUE 0
set_parameter_property start DISPLAY_NAME start
set_parameter_property start TYPE INTEGER
set_parameter_property start UNITS None
set_parameter_property start AFFECTS_GENERATION false
set_parameter_property start HDL_PARAMETER true
add_parameter start_read INTEGER 1
set_parameter_property start_read DEFAULT_VALUE 1
set_parameter_property start_read DISPLAY_NAME start_read
set_parameter_property start_read TYPE INTEGER
set_parameter_property start_read UNITS None
set_parameter_property start_read AFFECTS_GENERATION false
set_parameter_property start_read HDL_PARAMETER true
add_parameter start_end INTEGER 2
set_parameter_property start_end DEFAULT_VALUE 2
set_parameter_property start_end DISPLAY_NAME start_end
set_parameter_property start_end TYPE INTEGER
set_parameter_property start_end UNITS None
set_parameter_property start_end AFFECTS_GENERATION false
set_parameter_property start_end HDL_PARAMETER true
add_parameter start_low INTEGER 3
set_parameter_property start_low DEFAULT_VALUE 3
set_parameter_property start_low DISPLAY_NAME start_low
set_parameter_property start_low TYPE INTEGER
set_parameter_property start_low UNITS None
set_parameter_property start_low AFFECTS_GENERATION false
set_parameter_property start_low HDL_PARAMETER true
add_parameter start_high INTEGER 4
set_parameter_property start_high DEFAULT_VALUE 4
set_parameter_property start_high DISPLAY_NAME start_high
set_parameter_property start_high TYPE INTEGER
set_parameter_property start_high UNITS None
set_parameter_property start_high AFFECTS_GENERATION false
set_parameter_property start_high HDL_PARAMETER true
add_parameter bit_1_low INTEGER 5
set_parameter_property bit_1_low DEFAULT_VALUE 5
set_parameter_property bit_1_low DISPLAY_NAME bit_1_low
set_parameter_property bit_1_low TYPE INTEGER
set_parameter_property bit_1_low UNITS None
set_parameter_property bit_1_low AFFECTS_GENERATION false
set_parameter_property bit_1_low HDL_PARAMETER true
add_parameter bit_1_high INTEGER 6
set_parameter_property bit_1_high DEFAULT_VALUE 6
set_parameter_property bit_1_high DISPLAY_NAME bit_1_high
set_parameter_property bit_1_high TYPE INTEGER
set_parameter_property bit_1_high UNITS None
set_parameter_property bit_1_high AFFECTS_GENERATION false
set_parameter_property bit_1_high HDL_PARAMETER true
add_parameter bit_2_low INTEGER 7
set_parameter_property bit_2_low DEFAULT_VALUE 7
set_parameter_property bit_2_low DISPLAY_NAME bit_2_low
set_parameter_property bit_2_low TYPE INTEGER
set_parameter_property bit_2_low UNITS None
set_parameter_property bit_2_low AFFECTS_GENERATION false
set_parameter_property bit_2_low HDL_PARAMETER true
add_parameter bit_2_high INTEGER 8
set_parameter_property bit_2_high DEFAULT_VALUE 8
set_parameter_property bit_2_high DISPLAY_NAME bit_2_high
set_parameter_property bit_2_high TYPE INTEGER
set_parameter_property bit_2_high UNITS None
set_parameter_property bit_2_high AFFECTS_GENERATION false
set_parameter_property bit_2_high HDL_PARAMETER true
add_parameter bit_3_low INTEGER 9
set_parameter_property bit_3_low DEFAULT_VALUE 9
set_parameter_property bit_3_low DISPLAY_NAME bit_3_low
set_parameter_property bit_3_low TYPE INTEGER
set_parameter_property bit_3_low UNITS None
set_parameter_property bit_3_low AFFECTS_GENERATION false
set_parameter_property bit_3_low HDL_PARAMETER true
add_parameter bit_3_high INTEGER 10
set_parameter_property bit_3_high DEFAULT_VALUE 10
set_parameter_property bit_3_high DISPLAY_NAME bit_3_high
set_parameter_property bit_3_high TYPE INTEGER
set_parameter_property bit_3_high UNITS None
set_parameter_property bit_3_high AFFECTS_GENERATION false
set_parameter_property bit_3_high HDL_PARAMETER true
add_parameter bit_4_low INTEGER 11
set_parameter_property bit_4_low DEFAULT_VALUE 11
set_parameter_property bit_4_low DISPLAY_NAME bit_4_low
set_parameter_property bit_4_low TYPE INTEGER
set_parameter_property bit_4_low UNITS None
set_parameter_property bit_4_low AFFECTS_GENERATION false
set_parameter_property bit_4_low HDL_PARAMETER true
add_parameter bit_4_high INTEGER 12
set_parameter_property bit_4_high DEFAULT_VALUE 12
set_parameter_property bit_4_high DISPLAY_NAME bit_4_high
set_parameter_property bit_4_high TYPE INTEGER
set_parameter_property bit_4_high UNITS None
set_parameter_property bit_4_high AFFECTS_GENERATION false
set_parameter_property bit_4_high HDL_PARAMETER true
add_parameter bit_5_low INTEGER 13
set_parameter_property bit_5_low DEFAULT_VALUE 13
set_parameter_property bit_5_low DISPLAY_NAME bit_5_low
set_parameter_property bit_5_low TYPE INTEGER
set_parameter_property bit_5_low UNITS None
set_parameter_property bit_5_low AFFECTS_GENERATION false
set_parameter_property bit_5_low HDL_PARAMETER true
add_parameter bit_5_high INTEGER 14
set_parameter_property bit_5_high DEFAULT_VALUE 14
set_parameter_property bit_5_high DISPLAY_NAME bit_5_high
set_parameter_property bit_5_high TYPE INTEGER
set_parameter_property bit_5_high UNITS None
set_parameter_property bit_5_high AFFECTS_GENERATION false
set_parameter_property bit_5_high HDL_PARAMETER true
add_parameter bit_6_low INTEGER 15
set_parameter_property bit_6_low DEFAULT_VALUE 15
set_parameter_property bit_6_low DISPLAY_NAME bit_6_low
set_parameter_property bit_6_low TYPE INTEGER
set_parameter_property bit_6_low UNITS None
set_parameter_property bit_6_low AFFECTS_GENERATION false
set_parameter_property bit_6_low HDL_PARAMETER true
add_parameter bit_6_high INTEGER 16
set_parameter_property bit_6_high DEFAULT_VALUE 16
set_parameter_property bit_6_high DISPLAY_NAME bit_6_high
set_parameter_property bit_6_high TYPE INTEGER
set_parameter_property bit_6_high UNITS None
set_parameter_property bit_6_high AFFECTS_GENERATION false
set_parameter_property bit_6_high HDL_PARAMETER true
add_parameter bit_7_low INTEGER 17
set_parameter_property bit_7_low DEFAULT_VALUE 17
set_parameter_property bit_7_low DISPLAY_NAME bit_7_low
set_parameter_property bit_7_low TYPE INTEGER
set_parameter_property bit_7_low UNITS None
set_parameter_property bit_7_low AFFECTS_GENERATION false
set_parameter_property bit_7_low HDL_PARAMETER true
add_parameter bit_7_high INTEGER 18
set_parameter_property bit_7_high DEFAULT_VALUE 18
set_parameter_property bit_7_high DISPLAY_NAME bit_7_high
set_parameter_property bit_7_high TYPE INTEGER
set_parameter_property bit_7_high UNITS None
set_parameter_property bit_7_high AFFECTS_GENERATION false
set_parameter_property bit_7_high HDL_PARAMETER true
add_parameter bit_8_low INTEGER 19
set_parameter_property bit_8_low DEFAULT_VALUE 19
set_parameter_property bit_8_low DISPLAY_NAME bit_8_low
set_parameter_property bit_8_low TYPE INTEGER
set_parameter_property bit_8_low UNITS None
set_parameter_property bit_8_low AFFECTS_GENERATION false
set_parameter_property bit_8_low HDL_PARAMETER true
add_parameter bit_8_high INTEGER 20
set_parameter_property bit_8_high DEFAULT_VALUE 20
set_parameter_property bit_8_high DISPLAY_NAME bit_8_high
set_parameter_property bit_8_high TYPE INTEGER
set_parameter_property bit_8_high UNITS None
set_parameter_property bit_8_high AFFECTS_GENERATION false
set_parameter_property bit_8_high HDL_PARAMETER true
add_parameter bit_9_low INTEGER 21
set_parameter_property bit_9_low DEFAULT_VALUE 21
set_parameter_property bit_9_low DISPLAY_NAME bit_9_low
set_parameter_property bit_9_low TYPE INTEGER
set_parameter_property bit_9_low UNITS None
set_parameter_property bit_9_low AFFECTS_GENERATION false
set_parameter_property bit_9_low HDL_PARAMETER true
add_parameter bit_9_high INTEGER 22
set_parameter_property bit_9_high DEFAULT_VALUE 22
set_parameter_property bit_9_high DISPLAY_NAME bit_9_high
set_parameter_property bit_9_high TYPE INTEGER
set_parameter_property bit_9_high UNITS None
set_parameter_property bit_9_high AFFECTS_GENERATION false
set_parameter_property bit_9_high HDL_PARAMETER true
add_parameter bit_10_low INTEGER 23
set_parameter_property bit_10_low DEFAULT_VALUE 23
set_parameter_property bit_10_low DISPLAY_NAME bit_10_low
set_parameter_property bit_10_low TYPE INTEGER
set_parameter_property bit_10_low UNITS None
set_parameter_property bit_10_low AFFECTS_GENERATION false
set_parameter_property bit_10_low HDL_PARAMETER true
add_parameter bit_10_high INTEGER 24
set_parameter_property bit_10_high DEFAULT_VALUE 24
set_parameter_property bit_10_high DISPLAY_NAME bit_10_high
set_parameter_property bit_10_high TYPE INTEGER
set_parameter_property bit_10_high UNITS None
set_parameter_property bit_10_high AFFECTS_GENERATION false
set_parameter_property bit_10_high HDL_PARAMETER true
add_parameter bit_11_low INTEGER 25
set_parameter_property bit_11_low DEFAULT_VALUE 25
set_parameter_property bit_11_low DISPLAY_NAME bit_11_low
set_parameter_property bit_11_low TYPE INTEGER
set_parameter_property bit_11_low UNITS None
set_parameter_property bit_11_low AFFECTS_GENERATION false
set_parameter_property bit_11_low HDL_PARAMETER true
add_parameter bit_11_high INTEGER 26
set_parameter_property bit_11_high DEFAULT_VALUE 26
set_parameter_property bit_11_high DISPLAY_NAME bit_11_high
set_parameter_property bit_11_high TYPE INTEGER
set_parameter_property bit_11_high UNITS None
set_parameter_property bit_11_high AFFECTS_GENERATION false
set_parameter_property bit_11_high HDL_PARAMETER true
add_parameter bit_12_low INTEGER 27
set_parameter_property bit_12_low DEFAULT_VALUE 27
set_parameter_property bit_12_low DISPLAY_NAME bit_12_low
set_parameter_property bit_12_low TYPE INTEGER
set_parameter_property bit_12_low UNITS None
set_parameter_property bit_12_low AFFECTS_GENERATION false
set_parameter_property bit_12_low HDL_PARAMETER true
add_parameter bit_12_high INTEGER 28
set_parameter_property bit_12_high DEFAULT_VALUE 28
set_parameter_property bit_12_high DISPLAY_NAME bit_12_high
set_parameter_property bit_12_high TYPE INTEGER
set_parameter_property bit_12_high UNITS None
set_parameter_property bit_12_high AFFECTS_GENERATION false
set_parameter_property bit_12_high HDL_PARAMETER true
add_parameter bit_13_low INTEGER 29
set_parameter_property bit_13_low DEFAULT_VALUE 29
set_parameter_property bit_13_low DISPLAY_NAME bit_13_low
set_parameter_property bit_13_low TYPE INTEGER
set_parameter_property bit_13_low UNITS None
set_parameter_property bit_13_low AFFECTS_GENERATION false
set_parameter_property bit_13_low HDL_PARAMETER true
add_parameter bit_13_high INTEGER 30
set_parameter_property bit_13_high DEFAULT_VALUE 30
set_parameter_property bit_13_high DISPLAY_NAME bit_13_high
set_parameter_property bit_13_high TYPE INTEGER
set_parameter_property bit_13_high UNITS None
set_parameter_property bit_13_high AFFECTS_GENERATION false
set_parameter_property bit_13_high HDL_PARAMETER true
add_parameter bit_14_low INTEGER 31
set_parameter_property bit_14_low DEFAULT_VALUE 31
set_parameter_property bit_14_low DISPLAY_NAME bit_14_low
set_parameter_property bit_14_low TYPE INTEGER
set_parameter_property bit_14_low UNITS None
set_parameter_property bit_14_low AFFECTS_GENERATION false
set_parameter_property bit_14_low HDL_PARAMETER true
add_parameter bit_14_high INTEGER 32
set_parameter_property bit_14_high DEFAULT_VALUE 32
set_parameter_property bit_14_high DISPLAY_NAME bit_14_high
set_parameter_property bit_14_high TYPE INTEGER
set_parameter_property bit_14_high UNITS None
set_parameter_property bit_14_high AFFECTS_GENERATION false
set_parameter_property bit_14_high HDL_PARAMETER true
add_parameter bit_15_low INTEGER 33
set_parameter_property bit_15_low DEFAULT_VALUE 33
set_parameter_property bit_15_low DISPLAY_NAME bit_15_low
set_parameter_property bit_15_low TYPE INTEGER
set_parameter_property bit_15_low UNITS None
set_parameter_property bit_15_low AFFECTS_GENERATION false
set_parameter_property bit_15_low HDL_PARAMETER true
add_parameter bit_15_high INTEGER 34
set_parameter_property bit_15_high DEFAULT_VALUE 34
set_parameter_property bit_15_high DISPLAY_NAME bit_15_high
set_parameter_property bit_15_high TYPE INTEGER
set_parameter_property bit_15_high UNITS None
set_parameter_property bit_15_high AFFECTS_GENERATION false
set_parameter_property bit_15_high HDL_PARAMETER true
add_parameter bit_16_low INTEGER 35
set_parameter_property bit_16_low DEFAULT_VALUE 35
set_parameter_property bit_16_low DISPLAY_NAME bit_16_low
set_parameter_property bit_16_low TYPE INTEGER
set_parameter_property bit_16_low UNITS None
set_parameter_property bit_16_low AFFECTS_GENERATION false
set_parameter_property bit_16_low HDL_PARAMETER true
add_parameter bit_16_high INTEGER 36
set_parameter_property bit_16_high DEFAULT_VALUE 36
set_parameter_property bit_16_high DISPLAY_NAME bit_16_high
set_parameter_property bit_16_high TYPE INTEGER
set_parameter_property bit_16_high UNITS None
set_parameter_property bit_16_high AFFECTS_GENERATION false
set_parameter_property bit_16_high HDL_PARAMETER true
add_parameter bit_17_low INTEGER 37
set_parameter_property bit_17_low DEFAULT_VALUE 37
set_parameter_property bit_17_low DISPLAY_NAME bit_17_low
set_parameter_property bit_17_low TYPE INTEGER
set_parameter_property bit_17_low UNITS None
set_parameter_property bit_17_low AFFECTS_GENERATION false
set_parameter_property bit_17_low HDL_PARAMETER true
add_parameter bit_17_high INTEGER 38
set_parameter_property bit_17_high DEFAULT_VALUE 38
set_parameter_property bit_17_high DISPLAY_NAME bit_17_high
set_parameter_property bit_17_high TYPE INTEGER
set_parameter_property bit_17_high UNITS None
set_parameter_property bit_17_high AFFECTS_GENERATION false
set_parameter_property bit_17_high HDL_PARAMETER true
add_parameter bit_18_low INTEGER 39
set_parameter_property bit_18_low DEFAULT_VALUE 39
set_parameter_property bit_18_low DISPLAY_NAME bit_18_low
set_parameter_property bit_18_low TYPE INTEGER
set_parameter_property bit_18_low UNITS None
set_parameter_property bit_18_low AFFECTS_GENERATION false
set_parameter_property bit_18_low HDL_PARAMETER true
add_parameter bit_18_high INTEGER 40
set_parameter_property bit_18_high DEFAULT_VALUE 40
set_parameter_property bit_18_high DISPLAY_NAME bit_18_high
set_parameter_property bit_18_high TYPE INTEGER
set_parameter_property bit_18_high UNITS None
set_parameter_property bit_18_high AFFECTS_GENERATION false
set_parameter_property bit_18_high HDL_PARAMETER true
add_parameter bit_19_low INTEGER 41
set_parameter_property bit_19_low DEFAULT_VALUE 41
set_parameter_property bit_19_low DISPLAY_NAME bit_19_low
set_parameter_property bit_19_low TYPE INTEGER
set_parameter_property bit_19_low UNITS None
set_parameter_property bit_19_low AFFECTS_GENERATION false
set_parameter_property bit_19_low HDL_PARAMETER true
add_parameter bit_19_high INTEGER 42
set_parameter_property bit_19_high DEFAULT_VALUE 42
set_parameter_property bit_19_high DISPLAY_NAME bit_19_high
set_parameter_property bit_19_high TYPE INTEGER
set_parameter_property bit_19_high UNITS None
set_parameter_property bit_19_high AFFECTS_GENERATION false
set_parameter_property bit_19_high HDL_PARAMETER true
add_parameter bit_20_low INTEGER 43
set_parameter_property bit_20_low DEFAULT_VALUE 43
set_parameter_property bit_20_low DISPLAY_NAME bit_20_low
set_parameter_property bit_20_low TYPE INTEGER
set_parameter_property bit_20_low UNITS None
set_parameter_property bit_20_low AFFECTS_GENERATION false
set_parameter_property bit_20_low HDL_PARAMETER true
add_parameter bit_20_high INTEGER 44
set_parameter_property bit_20_high DEFAULT_VALUE 44
set_parameter_property bit_20_high DISPLAY_NAME bit_20_high
set_parameter_property bit_20_high TYPE INTEGER
set_parameter_property bit_20_high UNITS None
set_parameter_property bit_20_high AFFECTS_GENERATION false
set_parameter_property bit_20_high HDL_PARAMETER true
add_parameter bit_21_low INTEGER 45
set_parameter_property bit_21_low DEFAULT_VALUE 45
set_parameter_property bit_21_low DISPLAY_NAME bit_21_low
set_parameter_property bit_21_low TYPE INTEGER
set_parameter_property bit_21_low UNITS None
set_parameter_property bit_21_low AFFECTS_GENERATION false
set_parameter_property bit_21_low HDL_PARAMETER true
add_parameter bit_21_high INTEGER 46
set_parameter_property bit_21_high DEFAULT_VALUE 46
set_parameter_property bit_21_high DISPLAY_NAME bit_21_high
set_parameter_property bit_21_high TYPE INTEGER
set_parameter_property bit_21_high UNITS None
set_parameter_property bit_21_high AFFECTS_GENERATION false
set_parameter_property bit_21_high HDL_PARAMETER true
add_parameter bit_22_low INTEGER 47
set_parameter_property bit_22_low DEFAULT_VALUE 47
set_parameter_property bit_22_low DISPLAY_NAME bit_22_low
set_parameter_property bit_22_low TYPE INTEGER
set_parameter_property bit_22_low UNITS None
set_parameter_property bit_22_low AFFECTS_GENERATION false
set_parameter_property bit_22_low HDL_PARAMETER true
add_parameter bit_22_high INTEGER 48
set_parameter_property bit_22_high DEFAULT_VALUE 48
set_parameter_property bit_22_high DISPLAY_NAME bit_22_high
set_parameter_property bit_22_high TYPE INTEGER
set_parameter_property bit_22_high UNITS None
set_parameter_property bit_22_high AFFECTS_GENERATION false
set_parameter_property bit_22_high HDL_PARAMETER true
add_parameter bit_23_low INTEGER 49
set_parameter_property bit_23_low DEFAULT_VALUE 49
set_parameter_property bit_23_low DISPLAY_NAME bit_23_low
set_parameter_property bit_23_low TYPE INTEGER
set_parameter_property bit_23_low UNITS None
set_parameter_property bit_23_low AFFECTS_GENERATION false
set_parameter_property bit_23_low HDL_PARAMETER true
add_parameter bit_23_high INTEGER 50
set_parameter_property bit_23_high DEFAULT_VALUE 50
set_parameter_property bit_23_high DISPLAY_NAME bit_23_high
set_parameter_property bit_23_high TYPE INTEGER
set_parameter_property bit_23_high UNITS None
set_parameter_property bit_23_high AFFECTS_GENERATION false
set_parameter_property bit_23_high HDL_PARAMETER true
add_parameter bit_24_low INTEGER 51
set_parameter_property bit_24_low DEFAULT_VALUE 51
set_parameter_property bit_24_low DISPLAY_NAME bit_24_low
set_parameter_property bit_24_low TYPE INTEGER
set_parameter_property bit_24_low UNITS None
set_parameter_property bit_24_low AFFECTS_GENERATION false
set_parameter_property bit_24_low HDL_PARAMETER true
add_parameter bit_24_high INTEGER 52
set_parameter_property bit_24_high DEFAULT_VALUE 52
set_parameter_property bit_24_high DISPLAY_NAME bit_24_high
set_parameter_property bit_24_high TYPE INTEGER
set_parameter_property bit_24_high UNITS None
set_parameter_property bit_24_high AFFECTS_GENERATION false
set_parameter_property bit_24_high HDL_PARAMETER true
add_parameter bit_25_low INTEGER 53
set_parameter_property bit_25_low DEFAULT_VALUE 53
set_parameter_property bit_25_low DISPLAY_NAME bit_25_low
set_parameter_property bit_25_low TYPE INTEGER
set_parameter_property bit_25_low UNITS None
set_parameter_property bit_25_low AFFECTS_GENERATION false
set_parameter_property bit_25_low HDL_PARAMETER true
add_parameter bit_25_high INTEGER 54
set_parameter_property bit_25_high DEFAULT_VALUE 54
set_parameter_property bit_25_high DISPLAY_NAME bit_25_high
set_parameter_property bit_25_high TYPE INTEGER
set_parameter_property bit_25_high UNITS None
set_parameter_property bit_25_high AFFECTS_GENERATION false
set_parameter_property bit_25_high HDL_PARAMETER true
add_parameter bit_26_low INTEGER 55
set_parameter_property bit_26_low DEFAULT_VALUE 55
set_parameter_property bit_26_low DISPLAY_NAME bit_26_low
set_parameter_property bit_26_low TYPE INTEGER
set_parameter_property bit_26_low UNITS None
set_parameter_property bit_26_low AFFECTS_GENERATION false
set_parameter_property bit_26_low HDL_PARAMETER true
add_parameter bit_26_high INTEGER 56
set_parameter_property bit_26_high DEFAULT_VALUE 56
set_parameter_property bit_26_high DISPLAY_NAME bit_26_high
set_parameter_property bit_26_high TYPE INTEGER
set_parameter_property bit_26_high UNITS None
set_parameter_property bit_26_high AFFECTS_GENERATION false
set_parameter_property bit_26_high HDL_PARAMETER true
add_parameter bit_27_low INTEGER 57
set_parameter_property bit_27_low DEFAULT_VALUE 57
set_parameter_property bit_27_low DISPLAY_NAME bit_27_low
set_parameter_property bit_27_low TYPE INTEGER
set_parameter_property bit_27_low UNITS None
set_parameter_property bit_27_low AFFECTS_GENERATION false
set_parameter_property bit_27_low HDL_PARAMETER true
add_parameter bit_27_high INTEGER 58
set_parameter_property bit_27_high DEFAULT_VALUE 58
set_parameter_property bit_27_high DISPLAY_NAME bit_27_high
set_parameter_property bit_27_high TYPE INTEGER
set_parameter_property bit_27_high UNITS None
set_parameter_property bit_27_high AFFECTS_GENERATION false
set_parameter_property bit_27_high HDL_PARAMETER true
add_parameter bit_28_low INTEGER 59
set_parameter_property bit_28_low DEFAULT_VALUE 59
set_parameter_property bit_28_low DISPLAY_NAME bit_28_low
set_parameter_property bit_28_low TYPE INTEGER
set_parameter_property bit_28_low UNITS None
set_parameter_property bit_28_low AFFECTS_GENERATION false
set_parameter_property bit_28_low HDL_PARAMETER true
add_parameter bit_28_high INTEGER 60
set_parameter_property bit_28_high DEFAULT_VALUE 60
set_parameter_property bit_28_high DISPLAY_NAME bit_28_high
set_parameter_property bit_28_high TYPE INTEGER
set_parameter_property bit_28_high UNITS None
set_parameter_property bit_28_high AFFECTS_GENERATION false
set_parameter_property bit_28_high HDL_PARAMETER true
add_parameter bit_29_low INTEGER 61
set_parameter_property bit_29_low DEFAULT_VALUE 61
set_parameter_property bit_29_low DISPLAY_NAME bit_29_low
set_parameter_property bit_29_low TYPE INTEGER
set_parameter_property bit_29_low UNITS None
set_parameter_property bit_29_low AFFECTS_GENERATION false
set_parameter_property bit_29_low HDL_PARAMETER true
add_parameter bit_29_high INTEGER 62
set_parameter_property bit_29_high DEFAULT_VALUE 62
set_parameter_property bit_29_high DISPLAY_NAME bit_29_high
set_parameter_property bit_29_high TYPE INTEGER
set_parameter_property bit_29_high UNITS None
set_parameter_property bit_29_high AFFECTS_GENERATION false
set_parameter_property bit_29_high HDL_PARAMETER true
add_parameter bit_30_low INTEGER 63
set_parameter_property bit_30_low DEFAULT_VALUE 63
set_parameter_property bit_30_low DISPLAY_NAME bit_30_low
set_parameter_property bit_30_low TYPE INTEGER
set_parameter_property bit_30_low UNITS None
set_parameter_property bit_30_low AFFECTS_GENERATION false
set_parameter_property bit_30_low HDL_PARAMETER true
add_parameter bit_30_high INTEGER 64
set_parameter_property bit_30_high DEFAULT_VALUE 64
set_parameter_property bit_30_high DISPLAY_NAME bit_30_high
set_parameter_property bit_30_high TYPE INTEGER
set_parameter_property bit_30_high UNITS None
set_parameter_property bit_30_high AFFECTS_GENERATION false
set_parameter_property bit_30_high HDL_PARAMETER true
add_parameter bit_31_low INTEGER 65
set_parameter_property bit_31_low DEFAULT_VALUE 65
set_parameter_property bit_31_low DISPLAY_NAME bit_31_low
set_parameter_property bit_31_low TYPE INTEGER
set_parameter_property bit_31_low UNITS None
set_parameter_property bit_31_low AFFECTS_GENERATION false
set_parameter_property bit_31_low HDL_PARAMETER true
add_parameter bit_31_high INTEGER 66
set_parameter_property bit_31_high DEFAULT_VALUE 66
set_parameter_property bit_31_high DISPLAY_NAME bit_31_high
set_parameter_property bit_31_high TYPE INTEGER
set_parameter_property bit_31_high UNITS None
set_parameter_property bit_31_high AFFECTS_GENERATION false
set_parameter_property bit_31_high HDL_PARAMETER true
add_parameter bit_32_low INTEGER 67
set_parameter_property bit_32_low DEFAULT_VALUE 67
set_parameter_property bit_32_low DISPLAY_NAME bit_32_low
set_parameter_property bit_32_low TYPE INTEGER
set_parameter_property bit_32_low UNITS None
set_parameter_property bit_32_low AFFECTS_GENERATION false
set_parameter_property bit_32_low HDL_PARAMETER true
add_parameter bit_32_high INTEGER 68
set_parameter_property bit_32_high DEFAULT_VALUE 68
set_parameter_property bit_32_high DISPLAY_NAME bit_32_high
set_parameter_property bit_32_high TYPE INTEGER
set_parameter_property bit_32_high UNITS None
set_parameter_property bit_32_high AFFECTS_GENERATION false
set_parameter_property bit_32_high HDL_PARAMETER true
add_parameter ready INTEGER 90
set_parameter_property ready DEFAULT_VALUE 90
set_parameter_property ready DISPLAY_NAME ready
set_parameter_property ready TYPE INTEGER
set_parameter_property ready UNITS None
set_parameter_property ready AFFECTS_GENERATION false
set_parameter_property ready HDL_PARAMETER true
add_parameter time_2s INTEGER 2000000
set_parameter_property time_2s DEFAULT_VALUE 2000000
set_parameter_property time_2s DISPLAY_NAME time_2s
set_parameter_property time_2s TYPE INTEGER
set_parameter_property time_2s UNITS None
set_parameter_property time_2s AFFECTS_GENERATION false
set_parameter_property time_2s HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MRST
# | 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT

set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MCLK
# | 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0

set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ctrl
# | 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock MCLK
set_interface_property ctrl associatedReset MRST
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0

set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_writedata writedata Input 32
add_interface_port ctrl avs_ctrl_readdata readdata Output 32
add_interface_port ctrl avs_ctrl_byteenable byteenable Input 4
add_interface_port ctrl avs_ctrl_address address Input 3
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point AM2301
# | 
add_interface AM2301 conduit end

set_interface_property AM2301 ENABLED true

add_interface_port AM2301 sda export Bidir 1
add_interface_port AM2301 clk_1us export Output 1
# | 
# +-----------------------------------
