# TCL File Generated by Component Editor 11.1sp2
# Sun Jul 22 12:38:26 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | basic_FuncLED "RGB Function LED Controller" v1.0
# | Shyu Lee 2012.07.22.12:38:26
# | 
# | 
# | D:/Lophilo/grid/qsys_root/basic_FuncLED.v
# | 
# |    ./basic_FuncLED.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module basic_FuncLED
# | 
set_module_property NAME basic_FuncLED
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo/Basic
set_module_property AUTHOR "Shyu Lee"
set_module_property DISPLAY_NAME "RGB Function LED Controller"
set_module_property TOP_LEVEL_HDL_FILE basic_FuncLED.v
set_module_property TOP_LEVEL_HDL_MODULE basic_FuncLED
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME basic_FuncLED
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file basic_FuncLED.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MRST
# | 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT

set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MCLK
# | 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0

set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ctrl
# | 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock MCLK
set_interface_property ctrl associatedReset MRST
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0

set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_writedata writedata Input 32
add_interface_port ctrl avs_ctrl_readdata readdata Output 32
add_interface_port ctrl avs_ctrl_byteenable byteenable Input 4
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ledf
# | 
add_interface ledf avalon_streaming end
set_interface_property ledf associatedClock MCLK
set_interface_property ledf associatedReset MRST
set_interface_property ledf dataBitsPerSymbol 8
set_interface_property ledf errorDescriptor ""
set_interface_property ledf firstSymbolInHighOrderBits true
set_interface_property ledf maxChannel 0
set_interface_property ledf readyLatency 0

set_interface_property ledf ENABLED true

add_interface_port ledf asi_ledf_data data Input 24
add_interface_port ledf asi_ledf_valid valid Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT coe_LED_R export Output 1
add_interface_port EXPORT coe_LED_G export Output 1
add_interface_port EXPORT coe_LED_B export Output 1
# | 
# +-----------------------------------
