# TCL File Generated by Component Editor 11.1sp2
# Sun Jul 22 16:44:15 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | grid_PWM "PWM Output Controller" v1.0
# | Shyu Lee 2012.07.22.16:44:15
# | 
# | 
# | D:/Lophilo/grid/qsys_root/grid_PWM.v
# | 
# |    ./grid_PWM.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module grid_PWM
# | 
set_module_property NAME grid_PWM
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo/Grid
set_module_property AUTHOR "Shyu Lee"
set_module_property DISPLAY_NAME "PWM Output Controller"
set_module_property TOP_LEVEL_HDL_FILE grid_PWM.v
set_module_property TOP_LEVEL_HDL_MODULE grid_PWM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME grid_PWM
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file grid_PWM.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MRST
# | 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT

set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MCLK
# | 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0

set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pwm
# | 
add_interface pwm avalon end
set_interface_property pwm addressUnits WORDS
set_interface_property pwm associatedClock MCLK
set_interface_property pwm associatedReset MRST
set_interface_property pwm bitsPerSymbol 8
set_interface_property pwm burstOnBurstBoundariesOnly false
set_interface_property pwm burstcountUnits WORDS
set_interface_property pwm explicitAddressSpan 0
set_interface_property pwm holdTime 0
set_interface_property pwm linewrapBursts false
set_interface_property pwm maximumPendingReadTransactions 0
set_interface_property pwm readLatency 0
set_interface_property pwm readWaitTime 1
set_interface_property pwm setupTime 0
set_interface_property pwm timingUnits Cycles
set_interface_property pwm writeWaitTime 0

set_interface_property pwm ENABLED true

add_interface_port pwm avs_pwm_writedata writedata Input 32
add_interface_port pwm avs_pwm_readdata readdata Output 32
add_interface_port pwm avs_pwm_address address Input 3
add_interface_port pwm avs_pwm_byteenable byteenable Input 4
add_interface_port pwm avs_pwm_write write Input 1
add_interface_port pwm avs_pwm_read read Input 1
add_interface_port pwm avs_pwm_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point PWMRST
# | 
add_interface PWMRST reset end
set_interface_property PWMRST associatedClock PWMCLK
set_interface_property PWMRST synchronousEdges DEASSERT

set_interface_property PWMRST ENABLED true

add_interface_port PWMRST rsi_PWMRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point PWMCLK
# | 
add_interface PWMCLK clock end
set_interface_property PWMCLK clockRate 0

set_interface_property PWMCLK ENABLED true

add_interface_port PWMCLK csi_PWMCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fm
# | 
add_interface fm avalon_streaming end
set_interface_property fm associatedClock PWMCLK
set_interface_property fm associatedReset PWMRST
set_interface_property fm dataBitsPerSymbol 8
set_interface_property fm errorDescriptor ""
set_interface_property fm firstSymbolInHighOrderBits true
set_interface_property fm maxChannel 0
set_interface_property fm readyLatency 0

set_interface_property fm ENABLED true

add_interface_port fm asi_fm_data data Input 32
add_interface_port fm asi_fm_valid valid Input 1
add_interface_port fm asi_fm_ready ready Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pm
# | 
add_interface pm avalon_streaming end
set_interface_property pm associatedClock PWMCLK
set_interface_property pm associatedReset PWMRST
set_interface_property pm dataBitsPerSymbol 8
set_interface_property pm errorDescriptor ""
set_interface_property pm firstSymbolInHighOrderBits true
set_interface_property pm maxChannel 0
set_interface_property pm readyLatency 0

set_interface_property pm ENABLED true

add_interface_port pm asi_pm_data data Input 32
add_interface_port pm asi_pm_valid valid Input 1
add_interface_port pm asi_pm_ready ready Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point EXPORT
# | 
add_interface EXPORT conduit end

set_interface_property EXPORT ENABLED true

add_interface_port EXPORT coe_PWMOUT export Output 1
# | 
# +-----------------------------------
