# TCL File Generated by Component Editor 12.1sp1
# Sun Jul 21 17:47:09 CST 2013
# DO NOT MODIFY


# 
# qsys_serial_device "qsys_serial_device" v1.0
# zhizhou li 2013.07.21.17:47:09
# qsys serial device
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module qsys_serial_device
# 
set_module_property DESCRIPTION "qsys serial device"
set_module_property NAME qsys_serial_device
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo
set_module_property AUTHOR "zhizhou li"
set_module_property DISPLAY_NAME qsys_serial_device
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL qsys_serial_device
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file qsys_serial_device.v VERILOG PATH qsys_serial_device.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL qsys_serial_device
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file qsys_serial_device.v VERILOG PATH qsys_serial_device.v


# 
# parameters
# 
add_parameter address_size INTEGER 8
set_parameter_property address_size DEFAULT_VALUE 8
set_parameter_property address_size DISPLAY_NAME address_size
set_parameter_property address_size TYPE INTEGER
set_parameter_property address_size UNITS None
set_parameter_property address_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property address_size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point mrst
# 
add_interface mrst reset end
set_interface_property mrst associatedClock mclk
set_interface_property mrst synchronousEdges DEASSERT
set_interface_property mrst ENABLED true

add_interface_port mrst rsi_MRST_reset reset Input 1


# 
# connection point mclk
# 
add_interface mclk clock end
set_interface_property mclk clockRate 0
set_interface_property mclk ENABLED true

add_interface_port mclk csi_MCLK_clk clk Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock mclk
set_interface_property ctrl associatedReset mrst
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 1
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_writedata writedata Input 32
add_interface_port ctrl avs_ctrl_readdata readdata Output 32
add_interface_port ctrl avs_ctrl_byteenable byteenable Input 4
add_interface_port ctrl avs_ctrl_address address Input 8
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_waitrequest waitrequest Output 1
add_interface_port ctrl avs_ctrl_readdatavalid readdatavalid Output 1
add_interface_port ctrl avs_ctrl_chipselect chipselect Input 1
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock mclk
set_interface_property conduit_end associatedReset mrst
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end sdo export Output 1
add_interface_port conduit_end sdi export Input 1
add_interface_port conduit_end clk export Output 1
add_interface_port conduit_end sle export Output 1
add_interface_port conduit_end srdy export Input 1

