# TCL File Generated by Component Editor 12.1sp1
# Sun Jul 14 11:48:28 CST 2013
# DO NOT MODIFY


# 
# sht1x_sensor "sht1x_sensor" v1.0
# zhizhou li 2013.07.14.11:48:28
# sht1x sensor driver
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module sht1x_sensor
# 
set_module_property DESCRIPTION "sht1x sensor driver"
set_module_property NAME sht1x_sensor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo
set_module_property AUTHOR "zhizhou li"
set_module_property DISPLAY_NAME sht1x_sensor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sht1x_sensor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sht1x_sensor.v VERILOG PATH sht1x_sensor.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL sht1x_sensor
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sht1x_sensor.v VERILOG PATH sht1x_sensor.v


# 
# parameters
# 
add_parameter Address STD_LOGIC_VECTOR 0
set_parameter_property Address DEFAULT_VALUE 0
set_parameter_property Address DISPLAY_NAME Address
set_parameter_property Address TYPE STD_LOGIC_VECTOR
set_parameter_property Address ENABLED false
set_parameter_property Address UNITS None
set_parameter_property Address ALLOWED_RANGES 0:15
set_parameter_property Address HDL_PARAMETER true
add_parameter Measure_Temperature STD_LOGIC_VECTOR 3
set_parameter_property Measure_Temperature DEFAULT_VALUE 3
set_parameter_property Measure_Temperature DISPLAY_NAME Measure_Temperature
set_parameter_property Measure_Temperature TYPE STD_LOGIC_VECTOR
set_parameter_property Measure_Temperature ENABLED false
set_parameter_property Measure_Temperature UNITS None
set_parameter_property Measure_Temperature ALLOWED_RANGES 0:63
set_parameter_property Measure_Temperature HDL_PARAMETER true
add_parameter Measure_Relative_Humidity STD_LOGIC_VECTOR 5
set_parameter_property Measure_Relative_Humidity DEFAULT_VALUE 5
set_parameter_property Measure_Relative_Humidity DISPLAY_NAME Measure_Relative_Humidity
set_parameter_property Measure_Relative_Humidity TYPE STD_LOGIC_VECTOR
set_parameter_property Measure_Relative_Humidity ENABLED false
set_parameter_property Measure_Relative_Humidity UNITS None
set_parameter_property Measure_Relative_Humidity ALLOWED_RANGES 0:63
set_parameter_property Measure_Relative_Humidity HDL_PARAMETER true
add_parameter Read_Status_Register STD_LOGIC_VECTOR 7
set_parameter_property Read_Status_Register DEFAULT_VALUE 7
set_parameter_property Read_Status_Register DISPLAY_NAME Read_Status_Register
set_parameter_property Read_Status_Register TYPE STD_LOGIC_VECTOR
set_parameter_property Read_Status_Register ENABLED false
set_parameter_property Read_Status_Register UNITS None
set_parameter_property Read_Status_Register ALLOWED_RANGES 0:63
set_parameter_property Read_Status_Register HDL_PARAMETER true
add_parameter Write_Status_Register STD_LOGIC_VECTOR 6
set_parameter_property Write_Status_Register DEFAULT_VALUE 6
set_parameter_property Write_Status_Register DISPLAY_NAME Write_Status_Register
set_parameter_property Write_Status_Register TYPE STD_LOGIC_VECTOR
set_parameter_property Write_Status_Register ENABLED false
set_parameter_property Write_Status_Register UNITS None
set_parameter_property Write_Status_Register ALLOWED_RANGES 0:63
set_parameter_property Write_Status_Register HDL_PARAMETER true
add_parameter dir_out STD_LOGIC_VECTOR 1
set_parameter_property dir_out DEFAULT_VALUE 1
set_parameter_property dir_out DISPLAY_NAME dir_out
set_parameter_property dir_out TYPE STD_LOGIC_VECTOR
set_parameter_property dir_out ENABLED false
set_parameter_property dir_out UNITS None
set_parameter_property dir_out ALLOWED_RANGES 0:3
set_parameter_property dir_out HDL_PARAMETER true
add_parameter dir_in STD_LOGIC_VECTOR 0
set_parameter_property dir_in DEFAULT_VALUE 0
set_parameter_property dir_in DISPLAY_NAME dir_in
set_parameter_property dir_in TYPE STD_LOGIC_VECTOR
set_parameter_property dir_in ENABLED false
set_parameter_property dir_in UNITS None
set_parameter_property dir_in ALLOWED_RANGES 0:3
set_parameter_property dir_in HDL_PARAMETER true
add_parameter Reset_0 STD_LOGIC_VECTOR 0
set_parameter_property Reset_0 DEFAULT_VALUE 0
set_parameter_property Reset_0 DISPLAY_NAME Reset_0
set_parameter_property Reset_0 TYPE STD_LOGIC_VECTOR
set_parameter_property Reset_0 ENABLED false
set_parameter_property Reset_0 UNITS None
set_parameter_property Reset_0 ALLOWED_RANGES 0:262143
set_parameter_property Reset_0 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point mrst
# 
add_interface mrst reset end
set_interface_property mrst associatedClock mclk
set_interface_property mrst synchronousEdges DEASSERT
set_interface_property mrst ENABLED true

add_interface_port mrst rsi_MRST_reset reset Input 1


# 
# connection point mclk
# 
add_interface mclk clock end
set_interface_property mclk clockRate 0
set_interface_property mclk ENABLED true

add_interface_port mclk csi_MCLK_clk clk Input 1


# 
# connection point ctrl
# 
add_interface ctrl avalon end
set_interface_property ctrl addressUnits WORDS
set_interface_property ctrl associatedClock mclk
set_interface_property ctrl associatedReset mrst
set_interface_property ctrl bitsPerSymbol 8
set_interface_property ctrl burstOnBurstBoundariesOnly false
set_interface_property ctrl burstcountUnits WORDS
set_interface_property ctrl explicitAddressSpan 0
set_interface_property ctrl holdTime 0
set_interface_property ctrl linewrapBursts false
set_interface_property ctrl maximumPendingReadTransactions 0
set_interface_property ctrl readLatency 0
set_interface_property ctrl readWaitTime 1
set_interface_property ctrl setupTime 0
set_interface_property ctrl timingUnits Cycles
set_interface_property ctrl writeWaitTime 0
set_interface_property ctrl ENABLED true

add_interface_port ctrl avs_ctrl_writedata writedata Input 32
add_interface_port ctrl avs_ctrl_readdata readdata Output 32
add_interface_port ctrl avs_ctrl_byteenable byteenable Input 4
add_interface_port ctrl avs_ctrl_address address Input 3
add_interface_port ctrl avs_ctrl_write write Input 1
add_interface_port ctrl avs_ctrl_read read Input 1
add_interface_port ctrl avs_ctrl_waitrequest waitrequest Output 1
set_interface_assignment ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl embeddedsw.configuration.isPrintableDevice 0


# 
# connection point sh1x_sensor_output
# 
add_interface sh1x_sensor_output conduit end
set_interface_property sh1x_sensor_output associatedClock mclk
set_interface_property sh1x_sensor_output associatedReset mrst
set_interface_property sh1x_sensor_output ENABLED true

add_interface_port sh1x_sensor_output sck export Output 1
add_interface_port sh1x_sensor_output sda export Bidir 1
add_interface_port sh1x_sensor_output dir export Output 1

