# TCL File Generated by Component Editor 11.1sp2
# Sun Jul 22 12:46:21 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | test_LEDState "LED Test State Generator" v1.0
# | Shyu Lee 2012.07.22.12:46:21
# | 
# | 
# | D:/Lophilo/grid/qsys_root/test_LEDState.v
# | 
# |    ./test_LEDState.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module test_LEDState
# | 
set_module_property NAME test_LEDState
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo/Verification
set_module_property AUTHOR "Shyu Lee"
set_module_property DISPLAY_NAME "LED Test State Generator"
set_module_property TOP_LEVEL_HDL_FILE test_LEDState.v
set_module_property TOP_LEVEL_HDL_MODULE test_LEDState
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME test_LEDState
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file test_LEDState.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MRST
# | 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT

set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MCLK
# | 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0

set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fled0
# | 
add_interface fled0 avalon_streaming start
set_interface_property fled0 associatedClock MCLK
set_interface_property fled0 associatedReset MRST
set_interface_property fled0 dataBitsPerSymbol 8
set_interface_property fled0 errorDescriptor ""
set_interface_property fled0 firstSymbolInHighOrderBits true
set_interface_property fled0 maxChannel 0
set_interface_property fled0 readyLatency 0

set_interface_property fled0 ENABLED true

add_interface_port fled0 aso_fled0_data data Output 24
add_interface_port fled0 aso_fled0_valid valid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fled1
# | 
add_interface fled1 avalon_streaming start
set_interface_property fled1 associatedClock MCLK
set_interface_property fled1 associatedReset MRST
set_interface_property fled1 dataBitsPerSymbol 8
set_interface_property fled1 errorDescriptor ""
set_interface_property fled1 firstSymbolInHighOrderBits true
set_interface_property fled1 maxChannel 0
set_interface_property fled1 readyLatency 0

set_interface_property fled1 ENABLED true

add_interface_port fled1 aso_fled1_data data Output 24
add_interface_port fled1 aso_fled1_valid valid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fled2
# | 
add_interface fled2 avalon_streaming start
set_interface_property fled2 associatedClock MCLK
set_interface_property fled2 associatedReset MRST
set_interface_property fled2 dataBitsPerSymbol 8
set_interface_property fled2 errorDescriptor ""
set_interface_property fled2 firstSymbolInHighOrderBits true
set_interface_property fled2 maxChannel 0
set_interface_property fled2 readyLatency 0

set_interface_property fled2 ENABLED true

add_interface_port fled2 aso_fled2_data data Output 24
add_interface_port fled2 aso_fled2_valid valid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point fled3
# | 
add_interface fled3 avalon_streaming start
set_interface_property fled3 associatedClock MCLK
set_interface_property fled3 associatedReset MRST
set_interface_property fled3 dataBitsPerSymbol 8
set_interface_property fled3 errorDescriptor ""
set_interface_property fled3 firstSymbolInHighOrderBits true
set_interface_property fled3 maxChannel 0
set_interface_property fled3 readyLatency 0

set_interface_property fled3 ENABLED true

add_interface_port fled3 aso_fled3_data data Output 24
add_interface_port fled3 aso_fled3_valid valid Output 1
# | 
# +-----------------------------------
