# TCL File Generated by Component Editor 11.1sp2
# Sun Jul 22 12:24:57 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | test_RegRW32 "Register 32-bits RW Template" v1.0
# | Shyu Lee 2012.07.22.12:24:57
# | 
# | 
# | D:/Lophilo/grid/qsys_root/test_RegRW32.v
# | 
# |    ./test_RegRW32.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module test_RegRW32
# | 
set_module_property NAME test_RegRW32
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Lophilo/Verification
set_module_property AUTHOR "Shyu Lee"
set_module_property DISPLAY_NAME "Register 32-bits RW Template"
set_module_property TOP_LEVEL_HDL_FILE test_RegRW32.v
set_module_property TOP_LEVEL_HDL_MODULE test_RegRW32
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME test_RegRW32
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file test_RegRW32.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MRST
# | 
add_interface MRST reset end
set_interface_property MRST associatedClock MCLK
set_interface_property MRST synchronousEdges DEASSERT

set_interface_property MRST ENABLED true

add_interface_port MRST rsi_MRST_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point MCLK
# | 
add_interface MCLK clock end
set_interface_property MCLK clockRate 0

set_interface_property MCLK ENABLED true

add_interface_port MCLK csi_MCLK_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point test
# | 
add_interface test avalon end
set_interface_property test addressUnits WORDS
set_interface_property test associatedClock MCLK
set_interface_property test associatedReset MRST
set_interface_property test bitsPerSymbol 8
set_interface_property test burstOnBurstBoundariesOnly false
set_interface_property test burstcountUnits WORDS
set_interface_property test explicitAddressSpan 0
set_interface_property test holdTime 0
set_interface_property test linewrapBursts false
set_interface_property test maximumPendingReadTransactions 0
set_interface_property test readLatency 0
set_interface_property test readWaitTime 1
set_interface_property test setupTime 0
set_interface_property test timingUnits Cycles
set_interface_property test writeWaitTime 0

set_interface_property test ENABLED true

add_interface_port test avs_test_writedata writedata Input 32
add_interface_port test avs_test_readdata readdata Output 32
add_interface_port test avs_test_byteenable byteenable Input 4
add_interface_port test avs_test_write write Input 1
add_interface_port test avs_test_read read Input 1
add_interface_port test avs_test_waitrequest waitrequest Output 1
# | 
# +-----------------------------------
